"""tabelas iniciais

Revision ID: 91b462169336
Revises: 
Create Date: 2025-04-14 12:21:24.043458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b462169336'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_anexos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('caminho_arquivo', sa.String(), nullable=True),
    sa.Column('referencia_tipo', sa.String(), nullable=True),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('administrador', 'tecnico', name='tipousuario'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('contatos', sa.String(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificados_valvula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_inicio_calibracao', sa.Date(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('tag_equipamento', sa.String(), nullable=False),
    sa.Column('fabricante', sa.String(), nullable=True),
    sa.Column('modelo_valvula', sa.String(), nullable=True),
    sa.Column('diametro_valvula', sa.String(), nullable=True),
    sa.Column('pressao_abertura', sa.Float(), nullable=True),
    sa.Column('pressao_fechamento', sa.Float(), nullable=True),
    sa.Column('fluido_teste', sa.String(), nullable=True),
    sa.Column('unidade_pressao', sa.String(), nullable=True),
    sa.Column('foto_valvula', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laudos_nr13',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=True),
    sa.Column('tag_equipamento', sa.String(), nullable=True),
    sa.Column('foto_equipamento', sa.String(), nullable=True),
    sa.Column('data_inicio_inspecao', sa.Date(), nullable=True),
    sa.Column('tipo_inspecao', sa.String(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('fabricante', sa.String(), nullable=True),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('temperatura_max_projeto', sa.Float(), nullable=True),
    sa.Column('codigo_construcao', sa.String(), nullable=True),
    sa.Column('pmta_fabricante', sa.Float(), nullable=True),
    sa.Column('pth_fabricante', sa.Float(), nullable=True),
    sa.Column('fluido_servico', sa.String(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('tipo_vaso', sa.String(), nullable=True),
    sa.Column('classe_fluido', sa.String(), nullable=True),
    sa.Column('foto_pintura_revestimento', sa.String(), nullable=True),
    sa.Column('foto_placa_identificacao', sa.String(), nullable=True),
    sa.Column('foto_adesivo_categoria', sa.String(), nullable=True),
    sa.Column('foto_valvula_seguranca', sa.String(), nullable=True),
    sa.Column('foto_manometro', sa.String(), nullable=True),
    sa.Column('foto_medicao_espessura', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('comprimento', sa.Float(), nullable=True),
    sa.Column('diametro_vaso', sa.Float(), nullable=True),
    sa.Column('data_proxima_inspecao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_conformidade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laudo_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('conforme', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudos_nr13.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos_espessura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laudo_id', sa.UUID(), nullable=True),
    sa.Column('posicao', sa.String(), nullable=True),
    sa.Column('espessura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudos_nr13.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontos_espessura')
    op.drop_table('itens_conformidade')
    op.drop_table('laudos_nr13')
    op.drop_table('certificados_valvula')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('documentos_anexos')
    # ### end Alembic commands ###
